"""empty message

Revision ID: 50490f7f804e
Revises: 7a7b33e9b078
Create Date: 2024-08-21 20:46:34.803053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50490f7f804e'
down_revision = '7a7b33e9b078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_center', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('search_radius', sa.Integer(), nullable=False))
        batch_op.drop_column('radius_state')
        batch_op.drop_column('center_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_state', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('radius_state', sa.INTEGER(), server_default=sa.text('8047'), autoincrement=False, nullable=False))
        batch_op.drop_column('search_radius')
        batch_op.drop_column('search_center')

    # ### end Alembic commands ###
