"""added center_state and radius_state columns

Revision ID: 7a7b33e9b078
Revises: 09a5f81b7239
Create Date: 2024-08-21 20:34:01.933326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7b33e9b078'
down_revision = '09a5f81b7239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_state', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('radius_state', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('radius_state')
        batch_op.drop_column('center_state')

    # ### end Alembic commands ###
