"""changed expiration from dateTime to TIME

Revision ID: c0d90773ef05
Revises: 02381d77b85c
Create Date: 2024-08-17 18:04:07.520868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0d90773ef05'
down_revision = '02381d77b85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('expiration',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('expiration',
               existing_type=sa.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
